#!/usr/bin/env bash
set -euo pipefail

PL_FOLDER="${PL_FOLDER:-Omni3D_pl-ng-weighted}"
OUTPUT_DIR="${OUTPUT_DIR:-output/training/SUN_ng_weighted_depthreg_copgs}"
DEPTH_ROOT="${DEPTH_ROOT:-pseudo_label/SUNRGBD}"
DIST_URL="${DIST_URL:-tcp://0.0.0.0:12365}"
NUM_GPUS="${NUM_GPUS:-2}"

# Stable no-RSH route:
# ng-weighted pseudo labels + cached UniDepth depth consistency
# + factorized pseudo-label weights + MonoCoP-inspired CoP/GS.
# No pseudo masks are loaded and the Region Segmentation Head is disabled.
CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1}" python tools/train_net.py \
  --config-file configs/Base_Omni3D_SUN.yaml \
  --dist-url "${DIST_URL}" \
  --num-gpus "${NUM_GPUS}" \
  DATASETS.FOLDER_NAME "${PL_FOLDER}" \
  INPUT.USE_DEPTH True \
  INPUT.DEPTH_ROOT "${DEPTH_ROOT}" \
  INPUT.DEPTH_ALLOW_SENSOR_FALLBACK False \
  INPUT.USE_PSEUDO_MASK False \
  MODEL.ROI_CUBE_HEAD.USE_PSEUDO_WEIGHT False \
  MODEL.ROI_CUBE_HEAD.USE_FACTORIZED_PSEUDO_WEIGHT True \
  MODEL.ROI_CUBE_HEAD.USE_DEPTH_ROI False \
  MODEL.ROI_CUBE_HEAD.USE_ZERO_INIT_RESIDUAL False \
  MODEL.ROI_CUBE_HEAD.USE_REGION_SEGMENTATION_HEAD False \
  MODEL.ROI_CUBE_HEAD.USE_DEPTH_CONSISTENCY_LOSS True \
  MODEL.ROI_CUBE_HEAD.LOSS_W_DEPTH_CONSISTENCY 0.05 \
  MODEL.ROI_CUBE_HEAD.DEPTH_CONSISTENCY_MIN_PIXELS 16 \
  MODEL.ROI_CUBE_HEAD.DEPTH_CONSISTENCY_CENTER_CROP 1.0 \
  MODEL.ROI_CUBE_HEAD.DEPTH_CONSISTENCY_MODE front_surface \
  MODEL.ROI_CUBE_HEAD.DEPTH_CONSISTENCY_PERCENTILE 0.35 \
  MODEL.ROI_CUBE_HEAD.USE_COP_GS True \
  MODEL.ROI_CUBE_HEAD.COP_GS_HIDDEN_DIM 256 \
  MODEL.ROI_CUBE_HEAD.COP_GS_GATE_INIT_BIAS -2.0 \
  MODEL.ROI_CUBE_HEAD.COP_GS_SCALE_XY 0.20 \
  MODEL.ROI_CUBE_HEAD.COP_GS_SCALE_Z 0.20 \
  MODEL.ROI_CUBE_HEAD.COP_GS_SCALE_DIMS 0.20 \
  MODEL.ROI_CUBE_HEAD.COP_GS_SCALE_POSE 0.20 \
  MODEL.ROI_CUBE_HEAD.USE_GEOMETRY_INTERPRETER False \
  MODEL.EMA_TEACHER.ENABLED False \
  OUTPUT_DIR "${OUTPUT_DIR}" \
  "$@"
