#!/usr/bin/env bash
set -euo pipefail

PL_FOLDER="${PL_FOLDER:-Omni3D_pl-ng-weighted}"
OUTPUT_DIR="${OUTPUT_DIR:-output/training/SUN_ng_weighted_depthreg_zem}"
DEPTH_ROOT="${DEPTH_ROOT:-pseudo_label/SUNRGBD}"
MASK_ROOT="${MASK_ROOT:-pseudo_label/SUNRGBD}"
DIST_URL="${DIST_URL:-tcp://0.0.0.0:12372}"
NUM_GPUS="${NUM_GPUS:-2}"

# Stable DetAny3D-style ZEM ablation:
# - same pseudo labels/depth regularization line as ng_weighted_depthreg
# - no RSH, no CoP/GS, no latentbox
# - zero-init depth/ray/mask adapter before CubeHead, so iteration 0 matches
#   the original CubeHead feature.
CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1}" python tools/train_net.py \
  --config-file configs/Base_Omni3D_SUN.yaml \
  --dist-url "${DIST_URL}" \
  --num-gpus "${NUM_GPUS}" \
  DATASETS.FOLDER_NAME "${PL_FOLDER}" \
  INPUT.USE_DEPTH True \
  INPUT.DEPTH_ROOT "${DEPTH_ROOT}" \
  INPUT.DEPTH_ALLOW_SENSOR_FALLBACK False \
  INPUT.USE_PSEUDO_MASK True \
  INPUT.PSEUDO_MASK_ROOT "${MASK_ROOT}" \
  INPUT.PSEUDO_MASK_SIZE 28 \
  MODEL.ROI_CUBE_HEAD.USE_PSEUDO_WEIGHT False \
  MODEL.ROI_CUBE_HEAD.USE_FACTORIZED_PSEUDO_WEIGHT True \
  MODEL.ROI_CUBE_HEAD.USE_DEPTH_ROI False \
  MODEL.ROI_CUBE_HEAD.USE_ZERO_INIT_RESIDUAL False \
  MODEL.ROI_CUBE_HEAD.USE_REGION_SEGMENTATION_HEAD False \
  MODEL.ROI_CUBE_HEAD.USE_COP_GS False \
  MODEL.ROI_CUBE_HEAD.USE_GEOMETRY_INTERPRETER False \
  MODEL.ROI_CUBE_HEAD.USE_ZEM_ADAPTER True \
  MODEL.ROI_CUBE_HEAD.ZEM_HIDDEN_DIM 128 \
  MODEL.ROI_CUBE_HEAD.ZEM_ADAPTER_SCALE 1.0 \
  MODEL.ROI_CUBE_HEAD.ZEM_GATE_INIT_BIAS -2.0 \
  MODEL.ROI_CUBE_HEAD.ZEM_USE_DEPTH True \
  MODEL.ROI_CUBE_HEAD.ZEM_USE_RAY True \
  MODEL.ROI_CUBE_HEAD.ZEM_USE_MASK True \
  MODEL.ROI_CUBE_HEAD.ZEM_DETACH_GEOMETRY True \
  MODEL.ROI_CUBE_HEAD.USE_DEPTH_CONSISTENCY_LOSS True \
  MODEL.ROI_CUBE_HEAD.LOSS_W_DEPTH_CONSISTENCY 0.05 \
  MODEL.ROI_CUBE_HEAD.DEPTH_CONSISTENCY_MIN_PIXELS 16 \
  MODEL.ROI_CUBE_HEAD.DEPTH_CONSISTENCY_CENTER_CROP 0.75 \
  MODEL.ROI_CUBE_HEAD.DEPTH_CONSISTENCY_MODE front_surface \
  MODEL.ROI_CUBE_HEAD.DEPTH_CONSISTENCY_PERCENTILE 0.35 \
  OUTPUT_DIR "${OUTPUT_DIR}" \
  "$@"
