#!/usr/bin/env bash
set -euo pipefail

PL_FOLDER="${PL_FOLDER:-Omni3D_pl-distributional-anchor}"
OUTPUT_DIR="${OUTPUT_DIR:-output/training/SUN_distributional_anchor_depthreg}"
DEPTH_ROOT="${DEPTH_ROOT:-pseudo_label/SUNRGBD}"
DIST_URL="${DIST_URL:-tcp://0.0.0.0:12421}"
NUM_GPUS="${NUM_GPUS:-2}"

# Distributional latent-box training:
#   - main 3D target remains the stable source/ng-weighted pseudo box
#   - JSON top-K candidates are consumed by a soft-min distributional loss
#   - depth consistency and factorized weights keep the stable best route active
CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1}" python tools/train_net.py \
  --config-file configs/Base_Omni3D_SUN.yaml \
  --dist-url "${DIST_URL}" \
  --num-gpus "${NUM_GPUS}" \
  DATASETS.FOLDER_NAME "${PL_FOLDER}" \
  INPUT.USE_DEPTH True \
  INPUT.DEPTH_ROOT "${DEPTH_ROOT}" \
  INPUT.DEPTH_ALLOW_SENSOR_FALLBACK False \
  INPUT.USE_PSEUDO_MASK False \
  MODEL.ROI_CUBE_HEAD.USE_PSEUDO_WEIGHT False \
  MODEL.ROI_CUBE_HEAD.USE_FACTORIZED_PSEUDO_WEIGHT True \
  MODEL.ROI_CUBE_HEAD.USE_DISTRIBUTIONAL_PSEUDO_LABELS True \
  MODEL.ROI_CUBE_HEAD.DISTRIBUTIONAL_NUM_CANDIDATES "${DISTRIBUTIONAL_NUM_CANDIDATES:-8}" \
  MODEL.ROI_CUBE_HEAD.LOSS_W_DISTRIBUTIONAL "${LOSS_W_DISTRIBUTIONAL:-0.05}" \
  MODEL.ROI_CUBE_HEAD.DISTRIBUTIONAL_TEMPERATURE "${DISTRIBUTIONAL_TEMPERATURE:-0.20}" \
  MODEL.ROI_CUBE_HEAD.DISTRIBUTIONAL_USE_FACTORIZED_WEIGHT True \
  MODEL.ROI_CUBE_HEAD.USE_DEPTH_ROI False \
  MODEL.ROI_CUBE_HEAD.USE_ZERO_INIT_RESIDUAL False \
  MODEL.ROI_CUBE_HEAD.USE_REGION_SEGMENTATION_HEAD False \
  MODEL.ROI_CUBE_HEAD.USE_COP_GS False \
  MODEL.ROI_CUBE_HEAD.USE_ZEM_ADAPTER False \
  MODEL.ROI_CUBE_HEAD.USE_GEOMETRY_INTERPRETER False \
  MODEL.ROI_CUBE_HEAD.USE_PROJECTED_CORNER_DEPTH_AUX False \
  MODEL.ROI_CUBE_HEAD.USE_CORNER_HEATMAP_AUX False \
  MODEL.ROI_CUBE_HEAD.USE_DEPTH_CONSISTENCY_LOSS True \
  MODEL.ROI_CUBE_HEAD.LOSS_W_DEPTH_CONSISTENCY "${LOSS_W_DEPTH_CONSISTENCY:-0.05}" \
  MODEL.ROI_CUBE_HEAD.DEPTH_CONSISTENCY_MIN_PIXELS 16 \
  MODEL.ROI_CUBE_HEAD.DEPTH_CONSISTENCY_CENTER_CROP 0.75 \
  MODEL.ROI_CUBE_HEAD.DEPTH_CONSISTENCY_MODE front_surface \
  MODEL.ROI_CUBE_HEAD.DEPTH_CONSISTENCY_PERCENTILE 0.35 \
  MODEL.EMA_TEACHER.ENABLED False \
  OUTPUT_DIR "${OUTPUT_DIR}" \
  "$@"
