#!/usr/bin/env bash
set -euo pipefail

PL_FOLDER="${PL_FOLDER:-Omni3D_pl}"
OUTPUT_DIR="${OUTPUT_DIR:-output/training/SUN_zerolift}"
DEPTH_ROOT="${DEPTH_ROOT:-pseudo_label/SUNRGBD}"
DIST_URL="${DIST_URL:-tcp://0.0.0.0:12349}"

CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1}" python tools/train_net.py \
  --config-file configs/Base_Omni3D_SUN.yaml \
  --dist-url "${DIST_URL}" \
  --num-gpus 2 \
  DATASETS.FOLDER_NAME "${PL_FOLDER}" \
  INPUT.USE_DEPTH True \
  INPUT.DEPTH_ROOT "${DEPTH_ROOT}" \
  MODEL.ROI_CUBE_HEAD.USE_DEPTH_ROI True \
  MODEL.ROI_CUBE_HEAD.DEPTH_ADAPTER_SCALE 1.0 \
  MODEL.ROI_CUBE_HEAD.USE_ZERO_INIT_RESIDUAL True \
  MODEL.ROI_CUBE_HEAD.RESIDUAL_SCALE_XY 0.25 \
  MODEL.ROI_CUBE_HEAD.RESIDUAL_SCALE_Z 0.25 \
  MODEL.ROI_CUBE_HEAD.RESIDUAL_SCALE_DIMS 0.25 \
  MODEL.ROI_CUBE_HEAD.RESIDUAL_SCALE_POSE 0.25 \
  OUTPUT_DIR "${OUTPUT_DIR}"
