#!/usr/bin/env bash
set -euo pipefail

# LocateAnything3D-style lightweight Chain-of-Sight ablation.
#
# This route is intentionally independent from the existing MoCA3D-style,
# Detic+GroundingSAM fusion, and ZEM routes:
#   - no RSH
#   - no CoP/GS
#   - no ZEM
#   - no projected-corner / heatmap auxiliary loss
# It only adds a training-side curriculum on top of the stable
# ng-weighted + cached UniDepth + depth-consistency path.

PL_FOLDER="${PL_FOLDER:-Omni3D_pl-ng-weighted}"
OUTPUT_DIR="${OUTPUT_DIR:-output/training/SUN_ng_weighted_depthreg_locate3d_cos}"
DEPTH_ROOT="${DEPTH_ROOT:-pseudo_label/SUNRGBD}"
DIST_URL="${DIST_URL:-tcp://0.0.0.0:12386}"
NUM_GPUS="${NUM_GPUS:-2}"

CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1}" python tools/train_net.py \
  --config-file configs/Base_Omni3D_SUN.yaml \
  --dist-url "${DIST_URL}" \
  --num-gpus "${NUM_GPUS}" \
  DATASETS.FOLDER_NAME "${PL_FOLDER}" \
  INPUT.USE_DEPTH True \
  INPUT.DEPTH_ROOT "${DEPTH_ROOT}" \
  MODEL.ROI_CUBE_HEAD.USE_PSEUDO_WEIGHT False \
  MODEL.ROI_CUBE_HEAD.USE_FACTORIZED_PSEUDO_WEIGHT True \
  MODEL.ROI_CUBE_HEAD.USE_LOCATE3D_COS_CURRICULUM True \
  MODEL.ROI_CUBE_HEAD.LOCATE3D_NEAR_Z "${LOCATE3D_NEAR_Z:-1.0}" \
  MODEL.ROI_CUBE_HEAD.LOCATE3D_FAR_Z "${LOCATE3D_FAR_Z:-6.0}" \
  MODEL.ROI_CUBE_HEAD.LOCATE3D_MIN_NEAR_WEIGHT "${LOCATE3D_MIN_NEAR_WEIGHT:-0.55}" \
  MODEL.ROI_CUBE_HEAD.LOCATE3D_2D_IOU_WEIGHT "${LOCATE3D_2D_IOU_WEIGHT:-0.45}" \
  MODEL.ROI_CUBE_HEAD.LOCATE3D_GEOMETRY_WEIGHT "${LOCATE3D_GEOMETRY_WEIGHT:-0.35}" \
  MODEL.ROI_CUBE_HEAD.LOCATE3D_PSEUDO_WEIGHT "${LOCATE3D_PSEUDO_WEIGHT:-0.20}" \
  MODEL.ROI_CUBE_HEAD.LOCATE3D_XY_FLOOR "${LOCATE3D_XY_FLOOR:-0.80}" \
  MODEL.ROI_CUBE_HEAD.LOCATE3D_Z_FLOOR "${LOCATE3D_Z_FLOOR:-0.75}" \
  MODEL.ROI_CUBE_HEAD.LOCATE3D_DIMS_FLOOR "${LOCATE3D_DIMS_FLOOR:-0.45}" \
  MODEL.ROI_CUBE_HEAD.LOCATE3D_POSE_FLOOR "${LOCATE3D_POSE_FLOOR:-0.25}" \
  MODEL.ROI_CUBE_HEAD.LOCATE3D_JOINT_FLOOR "${LOCATE3D_JOINT_FLOOR:-0.40}" \
  MODEL.ROI_CUBE_HEAD.USE_DEPTH_ROI False \
  MODEL.ROI_CUBE_HEAD.USE_ZERO_INIT_RESIDUAL False \
  MODEL.ROI_CUBE_HEAD.USE_REGION_SEGMENTATION_HEAD False \
  MODEL.ROI_CUBE_HEAD.USE_COP_GS False \
  MODEL.ROI_CUBE_HEAD.USE_ZEM_ADAPTER False \
  MODEL.ROI_CUBE_HEAD.USE_GEOMETRY_INTERPRETER False \
  MODEL.ROI_CUBE_HEAD.USE_PROJECTED_CORNER_DEPTH_AUX False \
  MODEL.ROI_CUBE_HEAD.USE_CORNER_HEATMAP_AUX False \
  MODEL.ROI_CUBE_HEAD.USE_DEPTH_CONSISTENCY_LOSS True \
  MODEL.ROI_CUBE_HEAD.LOSS_W_DEPTH_CONSISTENCY "${LOSS_W_DEPTH_CONSISTENCY:-0.05}" \
  MODEL.ROI_CUBE_HEAD.DEPTH_CONSISTENCY_MIN_PIXELS 16 \
  MODEL.ROI_CUBE_HEAD.DEPTH_CONSISTENCY_CENTER_CROP 0.75 \
  MODEL.ROI_CUBE_HEAD.DEPTH_CONSISTENCY_MODE front_surface \
  MODEL.ROI_CUBE_HEAD.DEPTH_CONSISTENCY_PERCENTILE 0.35 \
  OUTPUT_DIR "${OUTPUT_DIR}"
