#!/usr/bin/env bash
set -euo pipefail

# Train with LocateAnything3D-style pseudo labels only.
# This uses the pseudo_weight_xy/z/dims/pose/joint fields generated by
# build_locate3d_cos_pseudolabels_sun.sh. It intentionally keeps other new
# modules off so this route measures pseudo-label quality rather than head
# changes.

PL_FOLDER="${PL_FOLDER:-Omni3D_pl-locate3d-cos}"
OUTPUT_DIR="${OUTPUT_DIR:-output/training/SUN_locate3d_cos_depthreg}"
DEPTH_ROOT="${DEPTH_ROOT:-pseudo_label/SUNRGBD}"
DIST_URL="${DIST_URL:-tcp://0.0.0.0:12387}"
NUM_GPUS="${NUM_GPUS:-2}"

CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1}" python tools/train_net.py \
  --config-file configs/Base_Omni3D_SUN.yaml \
  --dist-url "${DIST_URL}" \
  --num-gpus "${NUM_GPUS}" \
  DATASETS.FOLDER_NAME "${PL_FOLDER}" \
  INPUT.USE_DEPTH True \
  INPUT.DEPTH_ROOT "${DEPTH_ROOT}" \
  MODEL.ROI_CUBE_HEAD.USE_PSEUDO_WEIGHT False \
  MODEL.ROI_CUBE_HEAD.USE_FACTORIZED_PSEUDO_WEIGHT True \
  MODEL.ROI_CUBE_HEAD.USE_LOCATE3D_COS_CURRICULUM False \
  MODEL.ROI_CUBE_HEAD.USE_DEPTH_ROI False \
  MODEL.ROI_CUBE_HEAD.USE_ZERO_INIT_RESIDUAL False \
  MODEL.ROI_CUBE_HEAD.USE_REGION_SEGMENTATION_HEAD False \
  MODEL.ROI_CUBE_HEAD.USE_COP_GS False \
  MODEL.ROI_CUBE_HEAD.USE_ZEM_ADAPTER False \
  MODEL.ROI_CUBE_HEAD.USE_GEOMETRY_INTERPRETER False \
  MODEL.ROI_CUBE_HEAD.USE_PROJECTED_CORNER_DEPTH_AUX False \
  MODEL.ROI_CUBE_HEAD.USE_CORNER_HEATMAP_AUX False \
  MODEL.ROI_CUBE_HEAD.USE_DEPTH_CONSISTENCY_LOSS True \
  MODEL.ROI_CUBE_HEAD.LOSS_W_DEPTH_CONSISTENCY "${LOSS_W_DEPTH_CONSISTENCY:-0.05}" \
  MODEL.ROI_CUBE_HEAD.DEPTH_CONSISTENCY_MIN_PIXELS 16 \
  MODEL.ROI_CUBE_HEAD.DEPTH_CONSISTENCY_CENTER_CROP 0.75 \
  MODEL.ROI_CUBE_HEAD.DEPTH_CONSISTENCY_MODE front_surface \
  MODEL.ROI_CUBE_HEAD.DEPTH_CONSISTENCY_PERCENTILE 0.35 \
  OUTPUT_DIR "${OUTPUT_DIR}"
