#!/usr/bin/env bash
set -euo pipefail

PL_FOLDER="${PL_FOLDER:-Omni3D_pl-ng-weighted}"
OUTPUT_DIR="${OUTPUT_DIR:-output/training/SUN_latentbox_safe}"
DEPTH_ROOT="${DEPTH_ROOT:-pseudo_label/SUNRGBD}"
MASK_ROOT="${MASK_ROOT:-pseudo_label/SUNRGBD}"
DIST_URL="${DIST_URL:-tcp://0.0.0.0:12357}"
NUM_GPUS="${NUM_GPUS:-2}"

# Safe latent-box training:
# - Keep the original CubeHead prediction as the main path.
# - Use DINO/depth/mask geometry only as low-weight verifier losses.
# - Do not let geometry hypotheses overwrite final predictions until ablations
#   show that the branch is calibrated.
CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1}" python tools/train_net.py \
  --config-file configs/Base_Omni3D_SUN.yaml \
  --dist-url "${DIST_URL}" \
  --num-gpus "${NUM_GPUS}" \
  DATASETS.FOLDER_NAME "${PL_FOLDER}" \
  INPUT.USE_DEPTH True \
  INPUT.DEPTH_ROOT "${DEPTH_ROOT}" \
  INPUT.DEPTH_ALLOW_SENSOR_FALLBACK False \
  INPUT.USE_PSEUDO_MASK True \
  INPUT.PSEUDO_MASK_ROOT "${MASK_ROOT}" \
  INPUT.PSEUDO_MASK_SIZE 28 \
  INPUT.USE_GROUND_MASK True \
  INPUT.GROUND_MASK_ROOT "${MASK_ROOT}" \
  SOLVER.IMS_PER_BATCH 16 \
  SOLVER.BASE_LR 0.01 \
  SOLVER.MAX_ITER 43500 \
  SOLVER.STEPS "(26100,34800)" \
  SOLVER.WARMUP_ITERS 1359 \
  TEST.EVAL_PERIOD 10875 \
  MODEL.ROI_CUBE_HEAD.USE_PSEUDO_WEIGHT False \
  MODEL.ROI_CUBE_HEAD.USE_FACTORIZED_PSEUDO_WEIGHT True \
  MODEL.ROI_CUBE_HEAD.USE_DEPTH_ROI False \
  MODEL.ROI_CUBE_HEAD.USE_ZERO_INIT_RESIDUAL False \
  MODEL.ROI_CUBE_HEAD.USE_GEOMETRY_INTERPRETER True \
  MODEL.ROI_CUBE_HEAD.GEOMETRY_APPLY_TO_PREDICTION False \
  MODEL.ROI_CUBE_HEAD.GEOMETRY_APPLY_IN_INFERENCE False \
  MODEL.ROI_CUBE_HEAD.GEOMETRY_NUM_HYPOTHESES 8 \
  MODEL.ROI_CUBE_HEAD.GEOMETRY_HIDDEN_DIM 256 \
  MODEL.ROI_CUBE_HEAD.GEOMETRY_NUM_LAYERS 3 \
  MODEL.ROI_CUBE_HEAD.GEOMETRY_NUM_HEADS 8 \
  MODEL.ROI_CUBE_HEAD.GEOMETRY_RESIDUAL_SCALE 0.15 \
  MODEL.ROI_CUBE_HEAD.GEOMETRY_MIN_DIMENSION 0.03 \
  MODEL.ROI_CUBE_HEAD.GEOMETRY_MAX_DIMENSION 8.0 \
  MODEL.ROI_CUBE_HEAD.LOSS_W_MULTI_HYPOTHESIS 0.05 \
  MODEL.ROI_CUBE_HEAD.GEOMETRY_SELECTION_TEMPERATURE 0.20 \
  MODEL.ROI_CUBE_HEAD.GEOMETRY_ORACLE_WEIGHT 0.10 \
  MODEL.ROI_CUBE_HEAD.GEOMETRY_PROJECTION_WEIGHT 1.0 \
  MODEL.ROI_CUBE_HEAD.GEOMETRY_SILHOUETTE_WEIGHT 1.0 \
  MODEL.ROI_CUBE_HEAD.GEOMETRY_DEPTH_WEIGHT 1.0 \
  MODEL.ROI_CUBE_HEAD.GEOMETRY_POINT_WEIGHT 1.0 \
  MODEL.ROI_CUBE_HEAD.GEOMETRY_GROUND_WEIGHT 0.10 \
  MODEL.ROI_CUBE_HEAD.LOSS_W_GEOMETRY_CLOSURE 0.03 \
  MODEL.ROI_CUBE_HEAD.SHAPE_MEMORY_CAPACITY 2048 \
  MODEL.ROI_CUBE_HEAD.SHAPE_MEMORY_TOPK 8 \
  MODEL.ROI_CUBE_HEAD.SHAPE_MEMORY_MIN_CONFIDENCE 0.75 \
  MODEL.ROI_CUBE_HEAD.SHAPE_MEMORY_MAX_UPDATES 16 \
  MODEL.ROI_CUBE_HEAD.SHAPE_PROTOTYPE_BLEND 0.10 \
  MODEL.ROI_CUBE_HEAD.USE_DIFFERENTIABLE_RENDERER True \
  MODEL.ROI_CUBE_HEAD.RENDER_SIZE 28 \
  MODEL.ROI_CUBE_HEAD.LOSS_W_RENDER_SILHOUETTE 0.02 \
  MODEL.ROI_CUBE_HEAD.LOSS_W_RENDER_DEPTH 0.02 \
  MODEL.ROI_CUBE_HEAD.USE_DEPTH_CONSISTENCY_LOSS True \
  MODEL.ROI_CUBE_HEAD.LOSS_W_DEPTH_CONSISTENCY 0.05 \
  MODEL.ROI_CUBE_HEAD.DEPTH_CONSISTENCY_MODE front_surface \
  MODEL.ROI_CUBE_HEAD.DEPTH_CONSISTENCY_PERCENTILE 0.35 \
  MODEL.EMA_TEACHER.ENABLED False \
  OUTPUT_DIR "${OUTPUT_DIR}"
