"""
将 info_3d.pth 转换为完整格式的 Omni3D JSON 文件

与原版 SUNRGBD_val.json 格式一致，包含所有必需字段
"""

import json
import torch
import numpy as np
from pathlib import Path


# SUNRGBD 38 类别的类别映射
SUNRGBD_CATEGORIES = {
    'bicycle': 11, 'books': 14, 'bottle': 15, 'chair': 18, 'cup': 19,
    'laptop': 20, 'shoes': 21, 'towel': 22, 'blinds': 23, 'window': 24,
    'lamp': 25, 'shelves': 26, 'mirror': 27, 'sink': 28, 'cabinet': 29,
    'bathtub': 30, 'door': 31, 'toilet': 32, 'desk': 33, 'box': 34,
    'bookcase': 35, 'picture': 36, 'table': 37, 'counter': 38, 'bed': 39,
    'night stand': 40, 'pillow': 42, 'sofa': 43, 'television': 44,
    'floor mat': 45, 'curtain': 46, 'clothes': 47, 'stationery': 48,
    'refrigerator': 49, 'bin': 52, 'stove': 53, 'oven': 57, 'machine': 61
}

# COCO 格式 categories
COCO_CATEGORIES = [
    {"id": 11, "name": "bicycle", "supercategory": "object"},
    {"id": 14, "name": "books", "supercategory": "object"},
    {"id": 15, "name": "bottle", "supercategory": "object"},
    {"id": 18, "name": "chair", "supercategory": "furniture"},
    {"id": 19, "name": "cup", "supercategory": "object"},
    {"id": 20, "name": "laptop", "supercategory": "electronics"},
    {"id": 21, "name": "shoes", "supercategory": "object"},
    {"id": 22, "name": "towel", "supercategory": "object"},
    {"id": 23, "name": "blinds", "supercategory": "window"},
    {"id": 24, "name": "window", "supercategory": "furniture"},
    {"id": 25, "name": "lamp", "supercategory": "furniture"},
    {"id": 26, "name": "shelves", "supercategory": "furniture"},
    {"id": 27, "name": "mirror", "supercategory": "furniture"},
    {"id": 28, "name": "sink", "supercategory": "furniture"},
    {"id": 29, "name": "cabinet", "supercategory": "furniture"},
    {"id": 30, "name": "bathtub", "supercategory": "furniture"},
    {"id": 31, "name": "door", "supercategory": "furniture"},
    {"id": 32, "name": "toilet", "supercategory": "furniture"},
    {"id": 33, "name": "desk", "supercategory": "furniture"},
    {"id": 34, "name": "box", "supercategory": "object"},
    {"id": 35, "name": "bookcase", "supercategory": "furniture"},
    {"id": 36, "name": "picture", "supercategory": "object"},
    {"id": 37, "name": "table", "supercategory": "furniture"},
    {"id": 38, "name": "counter", "supercategory": "furniture"},
    {"id": 39, "name": "bed", "supercategory": "furniture"},
    {"id": 40, "name": "night stand", "supercategory": "furniture"},
    {"id": 42, "name": "pillow", "supercategory": "object"},
    {"id": 43, "name": "sofa", "supercategory": "furniture"},
    {"id": 44, "name": "television", "supercategory": "electronics"},
    {"id": 45, "name": "floor mat", "supercategory": "object"},
    {"id": 46, "name": "curtain", "supercategory": "furniture"},
    {"id": 47, "name": "clothes", "supercategory": "object"},
    {"id": 48, "name": "stationery", "supercategory": "object"},
    {"id": 49, "name": "refrigerator", "supercategory": "appliance"},
    {"id": 52, "name": "bin", "supercategory": "object"},
    {"id": 53, "name": "stove", "supercategory": "appliance"},
    {"id": 57, "name": "oven", "supercategory": "appliance"},
    {"id": 61, "name": "machine", "supercategory": "appliance"},
]


def tensor_to_list(obj):
    """将 numpy 数组或 tensor 转换为 Python list"""
    if isinstance(obj, np.ndarray):
        return obj.tolist()
    elif hasattr(obj, 'tolist'):
        return obj.tolist()
    elif isinstance(obj, list):
        return [tensor_to_list(item) for item in obj]
    else:
        return obj


def is_valid_3d(boxes3d):
    """检查 3D boxes 是否有效（全为 -1 表示无效）"""
    if boxes3d is None:
        return False
    boxes3d_flat = [x for box in boxes3d for x in box] if isinstance(boxes3d[0], list) else boxes3d
    return not all(x == -1 for x in boxes3d_flat)


def convert_pth_to_json(pth_path: str, output_path: str = None):
    """
    将 info_3d.pth 转换为完整格式的 JSON

    Args:
        pth_path: info_3d.pth 文件路径
        output_path: 输出 JSON 文件路径
    """
    print(f"📂 Loading from: {pth_path}")
    data = torch.load(pth_path, map_location='cpu')
    print(f"✅ Loaded {len(data)} images")

    # 构建 COCO 格式
    coco_data = {
        "info": "Pseudo labels generated by GSAM",
        "images": [],
        "annotations": [],
        "categories": COCO_CATEGORIES
    }

    annotation_id = 1
    all_category_ids = set()

    for image_id, result in data.items():
        metadata = result.get('_metadata', {})
        width = metadata.get('width', 640)
        height = metadata.get('height', 480)
        K = metadata.get('K', [[0, 0, 0], [0, 0, 0], [0, 0, 1]])
        dataset_id = metadata.get('dataset_id', 13)

        # 图片信息
        image_info = {
            "id": int(image_id),
            "width": width,
            "height": height,
            "file_path": f"SUNRGBD/kv2/kinect2data/.../{image_id}.jpg",
            "K": K,
            "src_90_rotate": 0,
            "src_flagged": False,
            "incomplete": False,
            "dataset_id": dataset_id
        }
        coco_data["images"].append(image_info)

        # 标注信息
        phrases = result.get('phrases', [])
        scores = result.get('conf', [])
        boxes = result.get('boxes', [])
        boxes3d = result.get('boxes3d', [])
        center_cam = result.get('center_cam', [])
        dimensions = result.get('dimensions', [])
        R_cam = result.get('R_cam', [])

        for i in range(len(phrases)):
            category_name = phrases[i]

            # 获取类别 ID
            category_id = SUNRGBD_CATEGORIES.get(category_name, -1)
            if category_id == -1:
                print(f"⚠️ Unknown category: '{category_name}', skipping")
                continue

            all_category_ids.add(category_id)

            # 处理嵌套列表（如 [[0.96]] 或 [0.96] 格式）
            def extract_float(val):
                if isinstance(val, list):
                    if len(val) == 1:
                        val = val[0]
                    if isinstance(val, list):
                        return float(val[0]) if val else 0.0
                return float(val)

            score = extract_float(scores[i]) if i < len(scores) else 1.0

            # 获取 3D 数据
            box3d = boxes3d[i] if i < len(boxes3d) else [[-1]*3]*8
            center = center_cam[i] if i < len(center_cam) else [-1, -1, -1]
            dim = dimensions[i] if i < len(dimensions) else [-1, -1, -1]
            r_cam = R_cam[i] if i < len(R_cam) else [[1,0,0],[0,1,0],[0,0,1]]

            # 转换 tensor 为 list
            box3d_list = tensor_to_list(box3d)
            center_list = tensor_to_list(center)
            dim_list = tensor_to_list(dim)
            r_cam_list = tensor_to_list(r_cam)

            # 检查 valid3D
            valid3d = is_valid_3d(box3d_list)

            # 获取 2D bbox
            box2d = boxes[i] if i < len(boxes) else [-1, -1, -1, -1]
            box2d_list = tensor_to_list(box2d)

            # 计算 COCO 格式的 bbox [x, y, w, h]
            x1, y1, x2, y2 = box2d_list[:4]
            bbox_coco = [float(x1), float(y1), float(x2 - x1), float(y2 - y1)]
            area = bbox_coco[2] * bbox_coco[3]

            # 使用 2D 检测框填充所有 2D bbox 字段
            bbox2d_tight = box2d_list[:4]

            annotation = {
                "id": annotation_id,
                "image_id": int(image_id),
                "dataset_id": dataset_id,
                "category_name": category_name,
                "category_id": category_id,
                "valid3D": valid3d,
                "bbox2D_tight": [float(x) for x in bbox2d_tight],  # 使用 2D 检测框
                "bbox2D_trunc": [float(x) for x in bbox2d_tight],  # 使用 2D 检测框
                "bbox2D_proj": [float(x) for x in bbox2d_tight],  # 使用 2D 检测框
                "bbox3D_cam": box3d_list,
                "center_cam": center_list,
                "dimensions": [float(x) for x in dim_list] if dim_list != [-1, -1, -1] else dim_list,
                "R_cam": r_cam_list,
                "behind_camera": False,
                "visibility": 1.0,
                "truncation": 0.0,
                "segmentation_pts": 1 if valid3d else 0,
                "lidar_pts": 1 if valid3d else 0,
                "depth_error": 0.0,
                "score": score,
                "bbox": bbox_coco,
                "area": area,
                "iscrowd": 0,
            }

            coco_data["annotations"].append(annotation)
            annotation_id += 1

    # 过滤 categories 只保留有标注的类别
    used_categories = [c for c in coco_data["categories"] if c["id"] in all_category_ids]
    coco_data["categories"] = used_categories

    # 设置输出路径
    if output_path is None:
        output_path = str(Path(pth_path).parent / "SUNRGBD_val_complete.json")

    # 保存
    print(f"💾 Saving to: {output_path}")
    with open(output_path, 'w') as f:
        json.dump(coco_data, f, indent=2)

    print(f"\n✅ Conversion complete!")
    print(f"   - Images: {len(coco_data['images'])}")
    print(f"   - Annotations: {len(coco_data['annotations'])}")
    print(f"   - Categories: {len(coco_data['categories'])}")
    print(f"   - Category IDs used: {sorted(all_category_ids)}")

    return coco_data


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Convert info_3d.pth to complete Omni3D JSON format")
    parser.add_argument("--input", type=str,
                        default="/data/ZhaoX/OVM3D-Dett/pseudo_label_gsam_val/info_3d.pth",
                        help="Input info_3d.pth file")
    parser.add_argument("--output", type=str, default=None,
                        help="Output JSON file")

    args = parser.parse_args()

    convert_pth_to_json(args.input, args.output)
