#!/usr/bin/env python
"""Build OVM3D-style 2D mask cache with GroundingDINO + SAM2.

This writes the same cache layout as the original Grounded-SAM script:

    pseudo_root/SUNRGBD/train/info.pth
    pseudo_root/SUNRGBD/train/mask/<image_id>.npy

The cache can then be consumed by the existing PCA/DFU pseudo-label builders.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

import numpy as np
import torch
from tqdm import tqdm


PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from tools.generate_pseudo_label_gsam import (  # noqa: E402
    ORIGINAL_BOX_THRESHOLD,
    ORIGINAL_IOU_THRESHOLD,
    ORIGINAL_TEXT_THRESHOLD,
    SUNRGBD_38_CLASSES,
    load_grounding_sam2_models,
    segment_with_grounding_sam2,
)
from grounding_dino.groundingdino.util.inference import load_image  # noqa: E402


def parse_args():
    parser = argparse.ArgumentParser("Build GroundingSAM2 cache for OVM3D")
    parser.add_argument("--dataset", default="SUNRGBD")
    parser.add_argument(
        "--splits",
        nargs="+",
        choices=["train", "val"],
        default=["train", "val"],
    )
    parser.add_argument("--image_root", default="datasets")
    parser.add_argument("--json_root", default="datasets/Omni3D")
    parser.add_argument("--output_root", default="pseudo_label_gsam2_udv2")
    parser.add_argument("--text_prompt", default=None)
    parser.add_argument("--box_threshold", type=float, default=ORIGINAL_BOX_THRESHOLD)
    parser.add_argument("--text_threshold", type=float, default=ORIGINAL_TEXT_THRESHOLD)
    parser.add_argument("--iou_threshold", type=float, default=ORIGINAL_IOU_THRESHOLD)
    parser.add_argument("--use_large_gdino", action="store_true")
    parser.add_argument("--grounding_dino_checkpoint", default=None)
    parser.add_argument("--sam_checkpoint", default=None)
    parser.add_argument("--resume", action="store_true")
    parser.add_argument("--max_images", type=int, default=None)
    parser.add_argument("--checkpoint_interval", type=int, default=100)
    parser.add_argument(
        "--copy_ground_from",
        default="pseudo_label",
        help=(
            "Copy existing ground cache from this pseudo root. Set empty string "
            "to skip. Object masks are still generated by GroundingSAM2."
        ),
    )
    return parser.parse_args()


def load_existing_info(info_path: Path):
    if not info_path.exists():
        return {}
    try:
        return torch.load(info_path, map_location="cpu", weights_only=False)
    except TypeError:
        return torch.load(info_path, map_location="cpu")


def copy_ground_cache(args, split: str):
    if not args.copy_ground_from:
        return

    src_dir = Path(args.copy_ground_from) / args.dataset / split
    dst_dir = Path(args.output_root) / args.dataset / split
    if not src_dir.exists():
        print(f"Ground cache source missing, skip: {src_dir}")
        return

    info_src = src_dir / "info_ground.pth"
    if info_src.exists():
        info_dst = dst_dir / "info_ground.pth"
        if not info_dst.exists():
            info_dst.write_bytes(info_src.read_bytes())

    ground_src = src_dir / "ground_mask"
    ground_dst = dst_dir / "ground_mask"
    if ground_src.exists() and not ground_dst.exists():
        import shutil

        shutil.copytree(ground_src, ground_dst)


def build_split_cache(args, split: str, gdino_model, sam2_predictor):
    text_prompt = args.text_prompt
    if text_prompt is None and args.dataset == "SUNRGBD":
        text_prompt = SUNRGBD_38_CLASSES
    if text_prompt is None:
        raise ValueError("--text_prompt is required for non-SUNRGBD datasets")
    valid_categories = [cat.strip() for cat in text_prompt.split(".") if cat.strip()]

    json_path = Path(args.json_root) / f"{args.dataset}_{split}.json"
    with open(json_path, "r") as f:
        data = json.load(f)

    images = list(data.get("images", []))
    if args.max_images is not None:
        images = images[: int(args.max_images)]

    out_dir = Path(args.output_root) / args.dataset / split
    mask_dir = out_dir / "mask"
    out_dir.mkdir(parents=True, exist_ok=True)
    mask_dir.mkdir(parents=True, exist_ok=True)
    info_path = out_dir / "info.pth"
    info = load_existing_info(info_path) if args.resume else {}

    processed_since_save = 0
    no_box = 0

    for img in tqdm(images, desc=f"GroundingSAM2 {split}"):
        image_id = int(img["id"])
        mask_path = mask_dir / f"{image_id}.npy"
        if args.resume and image_id in info and mask_path.exists():
            continue

        image_path = Path(args.image_root) / img["file_path"]
        try:
            image_source, image_transformed = load_image(str(image_path))
            result = segment_with_grounding_sam2(
                image_source=image_source,
                image_transformed=image_transformed,
                text_prompt=text_prompt,
                grounding_dino_model=gdino_model,
                sam2_predictor=sam2_predictor,
                box_threshold=float(args.box_threshold),
                text_threshold=float(args.text_threshold),
                iou_threshold=float(args.iou_threshold),
                valid_categories=valid_categories,
            )
        except Exception as exc:
            print(f"Failed {image_path}: {exc}")
            info[image_id] = {}
            no_box += 1
            continue

        if len(result["masks"]) == 0:
            info[image_id] = {}
            no_box += 1
        else:
            boxes = np.asarray(result["boxes"], dtype=np.float32).reshape(-1, 4)
            scores = np.asarray(result["scores"], dtype=np.float32).reshape(-1)
            phrases = [str(x).strip() for x in result["labels"]]
            masks = np.asarray(result["masks"], dtype=bool)
            np.save(mask_path, masks)
            info[image_id] = {
                "boxes": boxes,
                "conf": scores,
                "phrases": phrases,
                "proposal_sources": ["groundingsam2"] * len(phrases),
                "proposal_external_flags": np.zeros(len(phrases), dtype=bool),
                "proposal_source_indices": np.arange(len(phrases), dtype=np.int64),
            }

        processed_since_save += 1
        if processed_since_save >= int(args.checkpoint_interval):
            torch.save(info, info_path)
            processed_since_save = 0

    torch.save(info, info_path)
    copy_ground_cache(args, split)
    print(
        f"Wrote {info_path}: images={len(images)} cached={len(info)} "
        f"empty_or_failed={no_box}"
    )


def main():
    args = parse_args()
    print(f"Output root: {args.output_root}")
    print(f"CUDA_VISIBLE_DEVICES={os.environ.get('CUDA_VISIBLE_DEVICES', '')}")
    if args.dataset == "SUNRGBD" and args.text_prompt is None:
        print("Using fixed SUNRGBD 38-class prompt")

    gdino_model, sam2_predictor = load_grounding_sam2_models(
        grounding_dino_checkpoint=args.grounding_dino_checkpoint,
        sam_checkpoint=args.sam_checkpoint,
        use_large_gdino=bool(args.use_large_gdino),
    )

    for split in args.splits:
        build_split_cache(args, split, gdino_model, sam2_predictor)


if __name__ == "__main__":
    main()
